"""Canonical label vocabulary for the PlantWild classifier contract.

This module contains policy data, not translated UI copy. The final exported
checkpoint must provide this same ordered label set before it can be activated.
Only a reviewed glossary may add farmer-visible translations.
"""

PLANTWILD_CLASS_NAMES = (
    "apple black rot",
    "apple leaf",
    "apple mosaic virus",
    "apple rust",
    "apple scab",
    "banana leaf",
    "banana panama disease",
    "basil downy mildew",
    "basil leaf",
    "bean halo blight",
    "bean leaf",
    "bean mosaic virus",
    "bean rust",
    "bell pepper leaf",
    "bell pepper leaf spot",
    "blueberry leaf",
    "blueberry rust",
    "broccoli downy mildew",
    "broccoli leaf",
    "cabbage alternaria leaf spot",
    "cabbage leaf",
    "carrot cavity spot",
    "cauliflower alternaria leaf spot",
    "cauliflower leaf",
    "celery anthracnose",
    "celery early blight",
    "celery leaf",
    "cherry leaf",
    "cherry leaf spot",
    "cherry powdery mildew",
    "citrus canker",
    "citrus greening disease",
    "coffee leaf",
    "coffee leaf rust",
    "corn gray leaf spot",
    "corn leaf",
    "corn northern leaf blight",
    "corn rust",
    "corn smut",
    "cucumber angular leaf spot",
    "cucumber bacterial wilt",
    "cucumber leaf",
    "cucumber powdery mildew",
    "eggplant cercospora leaf spot",
    "eggplant leaf",
    "garlic leaf",
    "garlic leaf blight",
    "garlic rust",
    "ginger leaf",
    "ginger leaf spot",
    "ginger sheath blight",
    "grape black rot",
    "grape downy mildew",
    "grape leaf",
    "grape leaf spot",
    "grapevine leafroll disease",
    "lettuce downy mildew",
    "lettuce leaf",
    "lettuce mosaic virus",
    "maple leaf",
    "maple tar spot",
    "peach leaf",
    "peach leaf curl",
    "plum leaf",
    "plum pocket disease",
    "potato early blight",
    "potato late blight",
    "potato leaf",
    "raspberry leaf",
    "rice blast",
    "rice leaf",
    "rice sheath blight",
    "soybean leaf",
    "squash leaf",
    "squash powdery mildew",
    "strawberry anthracnose",
    "strawberry leaf",
    "strawberry leaf scorch",
    "tobacco leaf",
    "tobacco mosaic virus",
    "tomato bacterial leaf spot",
    "tomato early blight",
    "tomato late blight",
    "tomato leaf",
    "tomato leaf mold",
    "tomato mosaic virus",
    "tomato septoria leaf spot",
    "tomato yellow leaf curl virus",
    "zucchini yellow mosaic virus",
)

# Scientific/common aliases that may otherwise evade the canonical English
# labels. This is deliberately backend-owned. Additions require an agronomy
# review and tests; the language model cannot expand it at runtime.
PLANT_PATHOLOGY_ALIASES = (
    "Alternaria solani",
    "Alternaria alternata",
    "Phytophthora infestans",
    "Phytophthora",
    "Cercospora",
    "Septoria lycopersici",
    "Septoria",
    "Colletotrichum",
    "Puccinia",
    "Xanthomonas",
    "Pseudomonas syringae",
    "Ralstonia solanacearum",
    "Fusarium oxysporum",
    "Fusarium",
    "Plasmodiophora brassicae",
    "Ustilago maydis",
    "Taphrina deformans",
    "Venturia inaequalis",
    "Botrytis",
    "Rhizoctonia solani",
    "Magnaporthe oryzae",
    "Xylella fastidiosa",
)

PLANTWILD_DISEASE_LABELS = tuple(
    label for label in PLANTWILD_CLASS_NAMES if not label.endswith(" leaf")
)

assert len(PLANTWILD_CLASS_NAMES) == 89
